### ISSUE TITLE
INSTALL FILE???

### ISSUE THREAD

**Issue by MadLad1Clip** [jgpippin/sldb#1]
I am not able to find the install file or reuse the old file that was with this system before it got updated. Can anyone help me out as i am starting to loose it now with this.

**Comment by jgpippin** [comment]
The update obviates the need for a separate install file.  If you'll notice the instructions say to visit /path/to/sldb/install, not /path/to/sldb/install.php

**Comment by MadLad1Clip** [comment]
ok yeah i got that. I now i have the problem with this message

ERROR: NOT AUTHENTICATED

**Comment by MadLad1Clip** [comment]
I have followed all the steps given and dont know why I got this error can u help me out please. I am not good with php and the old system worked when I last used it but I dont know what I have dont wrong here.

**Comment by jgpippin** [comment]
Why upgrade from the old version if it worked for you? 

That error occurs when you don't have the correct mySQL credentials in the config.

**Comment by MadLad1Clip** [comment]
Yeah i no longer have the old files that worked when i searched for it i found the new ones but I can seem to work out why its doing this. I guess ill have to keep trying to work it out.

**Comment by MadLad1Clip** [comment]
Well after hours of checking all my settings reloading mysql and doing all that the readme says this system is not working i still get that error and I cant find out whats wrong i have followed it all and nothing still so guess this is not going to work for me and ill find something else.

**Comment by Tokuriku** [comment]
As it stands, it is impossible to create the table on the SQL database because the "index" file demands that any access to the page be authenticated. Since the password is passed through a special format address in the URL, even going to the page with a browser with the method "Install" does not work.

I personally commented the authentication request out to install and then uncommented it to have it work.
